# Generated by Django 4.2.7 on 2024-01-12 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_order_id_payment_company_remove_payment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user_course',
        ),
    ]
