# Generated by Django 4.2.7 on 2024-01-12 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_payment_course_remove_payment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='address_1',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='city',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='country',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order_comments',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='state',
        ),
    ]
